// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-subjects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_subjects_default = defineTool({
  name: "list_subjects",
  title: "List subjects",
  description: "List all NEET subjects (Physics, Chemistry, Biology) available in NEETVerse.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("subjects").select("id, name, slug").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { subjects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-chapters.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_chapters_default = defineTool2({
  name: "list_chapters",
  title: "List chapters",
  description: "List NEET chapters, optionally filtered by subject slug (physics, chemistry, biology).",
  inputSchema: {
    subject_slug: z.string().optional().describe("Optional subject slug filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject_slug }) => {
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let subjectId = null;
    if (subject_slug) {
      const { data: sub } = await sb.from("subjects").select("id").eq("slug", subject_slug).maybeSingle();
      if (!sub) return { content: [{ type: "text", text: `Unknown subject: ${subject_slug}` }], isError: true };
      subjectId = sub.id;
    }
    let q = sb.from("chapters").select("id, name, slug, subject_id").order("name");
    if (subjectId) q = q.eq("subject_id", subjectId);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { chapters: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-random-question.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_random_question_default = defineTool3({
  name: "get_random_question",
  title: "Get random practice question",
  description: "Fetch a random NEET practice question, optionally filtered by subject slug or chapter id.",
  inputSchema: {
    subject_slug: z2.string().optional().describe("Optional subject slug (physics/chemistry/biology)."),
    chapter_id: z2.string().uuid().optional().describe("Optional chapter UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ subject_slug, chapter_id }) => {
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let subjectId = null;
    if (subject_slug) {
      const { data: sub } = await sb.from("subjects").select("id").eq("slug", subject_slug).maybeSingle();
      if (sub) subjectId = sub.id;
    }
    let q = sb.from("questions").select("id, question_text, options, correct_option_index, explanation, chapter_id, subject_id").limit(50);
    if (chapter_id) q = q.eq("chapter_id", chapter_id);
    else if (subjectId) q = q.eq("subject_id", subjectId);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) return { content: [{ type: "text", text: "No questions found." }], isError: true };
    const pick = data[Math.floor(Math.random() * data.length)];
    return {
      content: [{ type: "text", text: JSON.stringify(pick) }],
      structuredContent: { question: pick }
    };
  }
});

// src/lib/mcp/tools/get-my-stats.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_stats_default = defineTool4({
  name: "get_my_stats",
  title: "Get my study stats",
  description: "Get the signed-in user's NEETVerse practice stats: total attempts, accuracy, current streak.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const userId = ctx.getUserId();
    const [{ data: answers }, { data: streak }] = await Promise.all([
      sb.from("attempt_answers").select("is_correct").eq("user_id", userId).limit(1e4),
      sb.from("user_streaks").select("current_streak, longest_streak, last_active_date").eq("user_id", userId).maybeSingle()
    ]);
    const total = answers?.length ?? 0;
    const correct = answers?.filter((a) => a.is_correct).length ?? 0;
    const accuracy = total ? Math.round(correct / total * 100) : 0;
    const stats = {
      total_answers: total,
      correct_answers: correct,
      accuracy_percent: accuracy,
      current_streak: streak?.current_streak ?? 0,
      longest_streak: streak?.longest_streak ?? 0,
      last_active_date: streak?.last_active_date ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sgmlggsgejdacztzmldb";
var mcp_default = defineMcp({
  name: "neetverse-mcp",
  title: "NEETVerse MCP",
  version: "0.1.0",
  instructions: "Tools for NEETVerse \u2014 a NEET (Physics, Chemistry, Biology) practice platform. Use `list_subjects` and `list_chapters` to browse the syllabus, `get_random_question` to pull a practice MCQ, and `get_my_stats` to view the signed-in student's accuracy and streak.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_subjects_default, list_chapters_default, get_random_question_default, get_my_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
